name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Deployable artifact name from upload-artifact step
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Deployable Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }} 
      - name: List files
        run: ls